### ISSUE TITLE
svg bree

### ISSUE THREAD

**Issue by ArhanSethi** [nohgo/CroomsCS#9]
<svg width="159" height="47" viewBox="0 0 159 47" fill="none" xmlns="http://www.w3.org/2000/svg">
<g filter="url(#filter0_d_50_23)">
<path d="M17.056 29.32V22.824H21.816V29.04C21.816 35.256 18.848 38.336 13.248 38.336C7.48 38.336 4.512 34.976 4.512 28.928V9.776C4.512 3.56 7.48 0.479999 13.08 0.479999C18.736 0.479999 21.816 3.56 21.816 9.72V14.144H17.056V9.72C17.056 6.808 15.768 5.184 13.248 5.184C10.784 5.184 9.496 6.752 9.496 9.664V29.32C9.496 32.176 10.616 33.688 13.248 33.688C15.768 33.688 17.056 32.288 17.056 29.32ZM41.1518 10.168V29.04C41.1518 35.256 38.0157 38.336 32.4157 38.336C26.6477 38.336 23.5117 34.976 23.5117 28.928V10.056C23.5117 4.008 26.7597 0.479999 32.3597 0.479999C37.9598 0.479999 41.1518 4.12 41.1518 10.168ZM36.2237 29.32V9.72C36.2237 6.808 34.8237 5.184 32.3037 5.184C29.8957 5.184 28.4957 6.752 28.4957 9.664V29.264C28.4957 32.176 29.8397 33.688 32.3597 33.688C34.8237 33.688 36.2237 32.288 36.2237 29.32ZM69.1688 38H64.6888V17.448C64.6888 15.152 64.7448 12.464 64.8568 9.384H64.6328L58.3608 38H53.7128L47.4408 9.384H47.2168C47.3288 12.464 47.3848 15.152 47.3848 17.448V38H42.9048V0.815998H50.5208L56.0088 28.088H56.2328L61.7208 0.815998H69.1688V38ZM81.4573 23.216H76.1373V38H71.0973V0.815998H81.4573C86.6093 0.815998 88.5133 3.56 88.5133 8.264V15.768C88.5133 20.472 86.6093 23.216 81.4573 23.216ZM76.1373 5.352V18.848H80.4493C82.8013 18.848 83.7533 17.448 83.7533 14.984V8.824C83.7533 6.584 82.8013 5.352 80.4493 5.352H76.1373ZM128.221 11.792H123.517V9.664C123.517 6.92 122.341 5.184 119.541 5.184C116.853 5.184 115.621 6.864 115.621 9.048V10.504C115.621 12.128 116.069 13.08 117.805 14.48C120.325 16.44 124.133 18.456 126.205 20.304C127.941 21.816 128.893 23.608 128.893 27.024V29.32C128.893 35.144 126.149 38.336 119.653 38.336C113.157 38.336 110.469 35.088 110.469 28.984V26.856H115.229V29.04C115.229 32.064 116.517 33.688 119.541 33.688C122.173 33.688 123.629 32.4 123.629 29.432V27.752C123.629 25.456 123.069 24.504 121.221 23.048C118.645 20.92 115.789 19.52 113.493 17.28C111.645 15.376 110.637 13.416 110.637 10.448V8.824C110.637 3.896 113.325 0.479999 119.485 0.479999C126.261 0.479999 128.221 4.568 128.221 10.168V11.792ZM143.117 29.32V22.824H147.877V29.04C147.877 35.256 144.909 38.336 139.309 38.336C133.541 38.336 130.573 34.976 130.573 28.928V9.776C130.573 3.56 133.541 0.479999 139.141 0.479999C144.797 0.479999 147.877 3.56 147.877 9.72V14.144H143.117V9.72C143.117 6.808 141.829 5.184 139.309 5.184C136.845 5.184 135.557 6.752 135.557 9.664V29.32C135.557 32.176 136.677 33.688 139.309 33.688C141.829 33.688 143.117 32.288 143.117 29.32ZM154.837 38H149.797V0.815998H154.837V38Z" fill="white"/>
<path d="M104.496 0.815998H109.424L102.48 18.68L109.648 38H104.496L99.5116 24.112H99.2876L94.2476 38H89.2076L96.3756 19.184L89.4316 0.815998H94.4716L99.3436 14.032H99.5676L104.496 0.815998Z" fill="#CF2C2C"/>
</g>
<defs>
<filter id="filter0_d_50_23" x="0.511963" y="0.47998" width="158.325" height="45.856" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
<feFlood flood-opacity="0" result="BackgroundImageFix"/>
<feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>
<feOffset dy="4"/>
<feGaussianBlur stdDeviation="2"/>
<feComposite in2="hardAlpha" operator="out"/>
<feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.25 0"/>
<feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_50_23"/>
<feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_50_23" result="shape"/>
</filter>
</defs>
</svg>

**Comment by ArhanSethi** [comment]
<svg width="159" height="47" viewBox="0 0 159 47" fill="none" xmlns="http://www.w3.org/2000/svg">
<g filter="url(#filter0_d_50_23)">
<path d="M17.056 29.32V22.824H21.816V29.04C21.816 35.256 18.848 38.336 13.248 38.336C7.48 38.336 4.512 34.976 4.512 28.928V9.776C4.512 3.56 7.48 0.479999 13.08 0.479999C18.736 0.479999 21.816 3.56 21.816 9.72V14.144H17.056V9.72C17.056 6.808 15.768 5.184 13.248 5.184C10.784 5.184 9.496 6.752 9.496 9.664V29.32C9.496 32.176 10.616 33.688 13.248 33.688C15.768 33.688 17.056 32.288 17.056 29.32ZM41.1518 10.168V29.04C41.1518 35.256 38.0157 38.336 32.4157 38.336C26.6477 38.336 23.5117 34.976 23.5117 28.928V10.056C23.5117 4.008 26.7597 0.479999 32.3597 0.479999C37.9598 0.479999 41.1518 4.12 41.1518 10.168ZM36.2237 29.32V9.72C36.2237 6.808 34.8237 5.184 32.3037 5.184C29.8957 5.184 28.4957 6.752 28.4957 9.664V29.264C28.4957 32.176 29.8397 33.688 32.3597 33.688C34.8237 33.688 36.2237 32.288 36.2237 29.32ZM69.1688 38H64.6888V17.448C64.6888 15.152 64.7448 12.464 64.8568 9.384H64.6328L58.3608 38H53.7128L47.4408 9.384H47.2168C47.3288 12.464 47.3848 15.152 47.3848 17.448V38H42.9048V0.815998H50.5208L56.0088 28.088H56.2328L61.7208 0.815998H69.1688V38ZM81.4573 23.216H76.1373V38H71.0973V0.815998H81.4573C86.6093 0.815998 88.5133 3.56 88.5133 8.264V15.768C88.5133 20.472 86.6093 23.216 81.4573 23.216ZM76.1373 5.352V18.848H80.4493C82.8013 18.848 83.7533 17.448 83.7533 14.984V8.824C83.7533 6.584 82.8013 5.352 80.4493 5.352H76.1373ZM128.221 11.792H123.517V9.664C123.517 6.92 122.341 5.184 119.541 5.184C116.853 5.184 115.621 6.864 115.621 9.048V10.504C115.621 12.128 116.069 13.08 117.805 14.48C120.325 16.44 124.133 18.456 126.205 20.304C127.941 21.816 128.893 23.608 128.893 27.024V29.32C128.893 35.144 126.149 38.336 119.653 38.336C113.157 38.336 110.469 35.088 110.469 28.984V26.856H115.229V29.04C115.229 32.064 116.517 33.688 119.541 33.688C122.173 33.688 123.629 32.4 123.629 29.432V27.752C123.629 25.456 123.069 24.504 121.221 23.048C118.645 20.92 115.789 19.52 113.493 17.28C111.645 15.376 110.637 13.416 110.637 10.448V8.824C110.637 3.896 113.325 0.479999 119.485 0.479999C126.261 0.479999 128.221 4.568 128.221 10.168V11.792ZM143.117 29.32V22.824H147.877V29.04C147.877 35.256 144.909 38.336 139.309 38.336C133.541 38.336 130.573 34.976 130.573 28.928V9.776C130.573 3.56 133.541 0.479999 139.141 0.479999C144.797 0.479999 147.877 3.56 147.877 9.72V14.144H143.117V9.72C143.117 6.808 141.829 5.184 139.309 5.184C136.845 5.184 135.557 6.752 135.557 9.664V29.32C135.557 32.176 136.677 33.688 139.309 33.688C141.829 33.688 143.117 32.288 143.117 29.32ZM154.837 38H149.797V0.815998H154.837V38Z" fill="white"/>
<path d="M104.496 0.815998H109.424L102.48 18.68L109.648 38H104.496L99.5116 24.112H99.2876L94.2476 38H89.2076L96.3756 19.184L89.4316 0.815998H94.4716L99.3436 14.032H99.5676L104.496 0.815998Z" fill="#CF2C2C"/>
</g>
<defs>
<filter id="filter0_d_50_23" x="0.511963" y="0.47998" width="158.325" height="45.856" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
<feFlood flood-opacity="0" result="BackgroundImageFix"/>
<feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>
<feOffset dy="4"/>
<feGaussianBlur stdDeviation="2"/>
<feComposite in2="hardAlpha" operator="out"/>
<feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.25 0"/>
<feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_50_23"/>
<feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_50_23" result="shape"/>
</filter>
</defs>
</svg>

**Comment by nohgo** [comment]
you suck

**Comment by ArhanSethi** [comment]
.navbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  background: #252525;
  padding: 10px;
  margin: 0;
}

.logo {
  margin-left: 10px;
  padding: 0;
}

**Comment by ArhanSethi** [comment]
.nav-buttons {
  margin-right: 10px;
}

.nav-buttons a {
  color: white;
  text-decoration: none;
  font-size: 22px;
  font-family: Helvetica;
  font-weight: 700;
  word-wrap: break-word;
  margin: 0 5px;
}

.nav-buttons a.active {
  background-color: white;
}

**Comment by ArhanSethi** [comment]
<div class="nav-buttons">
      <a href="#">HOME</a>
      <a href="#">ABOUT</a>
      <a href="#">EXPLORE</a>
    </div>

**Comment by ArhanSethi** [comment]
`<div class="nav-buttons">
      <a href="#">HOME</a>
      <a href="#">ABOUT</a>
      <a href="#">EXPLORE</a>
    </div>`

**Comment by ArhanSethi** [comment]
`color: #FFF;
font-family: Montserrat;
font-size: 24px;
font-style: normal;
font-weight: 600;
line-height: normal;`
